auth:
  permitall:
    -
      pattern: /login/**
    -
      pattern: /blog/**
    -
      pattern: /fallbackcontroller
    -
      pattern: /web/**

gateway:
  limit:
    redis-rate: # token
      replenish-rate: 10
      burst-capacity: 3000
    throttle: # leaky
      capacity: 10000
      refill-tokens: 50
      refill-period: 5


security:
  oauth2:
    client:
      accessTokenUri: /oauth/token
      clientId: gateway
      clientSecret: gateway
    resource:
      userInfoUri: /user
      token-info-uri: /oauth/check_token

---

spring:
  redis:
    host: localhost
    port: 6379
  cloud:
#    globalcors:
#      corsConfigurations:
#        '[/**]':
#          allowedOrigins: "blueskykong.com"
#          allowedMethods:
#          - GET
    gateway:
      loadbalancer:
        use404: true
      discovery:
        locator:
          enabled: true
      default-filters:
      - AddRequestHeader=X-Request-Foo, Bar
      - name: RequestRateLimiter
        args:
          key-resolver: "#{@remoteAddrKeyResolver}"
          rate-limiter: "#{@customRateLimiter}"   # token

      routes:
      - id: ingredients-fallback
        uri: http://localhost:9099
        predicates:
          - Path=/fallbackcontroller
        filters:
        - name: FallbackHeaders
          args:
            executionExceptionTypeHeaderName: X-Exception-Header
            executionExceptionMessageHeaderName: X-Exception-Message
            rootCauseExceptionTypeHeaderName: X-Root-Exception-Header
            rootCauseExceptionMessageHeaderName: X-Root-Exception-Message
      # =====================================
      - id: service_to_web
        uri: lb://authdemo
        predicates:
        - Path=/web/**
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallbackcontroller
        - StripPrefix=1
      - id: service_to_auth
        uri: lb://auth
        order: 9000
        predicates:
        - Path=/login/**
        filters:
        - StripPrefix=1
      # =====================================
      - id: default_path_to_error
        uri: http://localhost:9099/error
        order: 10000
        predicates:
        - Path=/**
        filters:
        - AddRequestParameter=foo, bar


hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 8000