mysql-auth:
  restart: always
  image: mysql:5.7
  ports:
    - "3316:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=_123456_
    - MYSQL_DATABASE=auth

consul:
  container_name: mc-consul
  image: 'consul:0.8.5'
  ports:
    - '8500:8500'
    - '8300:8300'

redis:
  container_name: auth-redis
  image: 'redis:4'
  ports:
    - '6379:6379'
