spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3316/auth?autoReconnect=true&useSSL=false
    username: root
    password: _123456_

############################# Redis config #############################
cache:
  # pool config
  pool:
    maxIdle: 15
    maxTotal: 30
    maxWaitMillis: 6000
    minIdle: 1
    numTestsPerEvictionRun: 10
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 6000
  # enable redis
  redis:
    enabled: true
redis:
  database: 0
  host:
    address: localhost
    port: 6379
  setup:
    flushdb: true

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000

