auth:
  permitall:
    -
      pattern: /login/**
    -
      pattern: /web/**


zuul:
  ribbon:
    eager-load:
      enabled: true     #zuul饥饿加载
  host:
    maxTotalConnections: 200
    maxPerRouteConnections: 20
  routes:
    demo:
      path: /web/**
      ignoredPatterns: /consul
      serviceId: authdemo
      sensitiveHeaders: Cookie,Set-Cookie
    auth:
      path: /login/**
      ignoredPatterns: /consul
      serviceId: auth
      sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 1000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 1000


security:
  oauth2:
    client:
      accessTokenUri: /oauth/token
      clientId: frontend
      clientSecret: frontend
    resource:
      userInfoUri: /user
      token-info-uri: /oauth/check_token
  filter-order: 1